set(__QT_DEPLOY_TARGET_x4_core_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/core/libx4_core.a)
set(__QT_DEPLOY_TARGET_x4_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_x4_network_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/network/libx4_network.a)
set(__QT_DEPLOY_TARGET_x4_network_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_x4_auth_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/auth/libx4_auth.a)
set(__QT_DEPLOY_TARGET_x4_auth_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_x4_modrinth_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/modrinth/libx4_modrinth.a)
set(__QT_DEPLOY_TARGET_x4_modrinth_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_x4_java_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/java/libx4_java.a)
set(__QT_DEPLOY_TARGET_x4_java_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_x4_cache_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/cache/libx4_cache.a)
set(__QT_DEPLOY_TARGET_x4_cache_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_x4_instance_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/instance/libx4_instance.a)
set(__QT_DEPLOY_TARGET_x4_instance_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_x4_launch_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/launch/libx4_launch.a)
set(__QT_DEPLOY_TARGET_x4_launch_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_x4_ui_FILE /home/x4/Documentos/X4Launcher C++/build_windows/src/ui/libx4_ui.a)
set(__QT_DEPLOY_TARGET_x4_ui_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_launch_tester_FILE /home/x4/Documentos/X4Launcher C++/build_windows/tools/launch_tester.exe)
set(__QT_DEPLOY_TARGET_launch_tester_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_launch_tester_RUNTIME_DLLS /usr/lib/libQt6Concurrent.so.6.11.0;/usr/lib/libQt6Network.so.6.11.0;/usr/lib/libQt6Gui.so.6.11.0;/usr/lib/libQt6DBus.so.6.11.0;/usr/lib/libQt6Core.so.6.11.0)
set(__QT_DEPLOY_TARGET_X4Launcher_FILE /home/x4/Documentos/X4Launcher C++/build_windows/X4Launcher.exe)
set(__QT_DEPLOY_TARGET_X4Launcher_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_X4Launcher_RUNTIME_DLLS /usr/lib/libQt6Widgets.so.6.11.0;/usr/lib/libQt6Concurrent.so.6.11.0;/usr/lib/libQt6Network.so.6.11.0;/usr/lib/libQt6Gui.so.6.11.0;/usr/lib/libQt6DBus.so.6.11.0;/usr/lib/libQt6Core.so.6.11.0)
